#!/bin/bash
set -e

stateFile=".state"

declare -A gitPathes

function getDir () {
  # Taken from https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
  local SOURCE="${BASH_SOURCE[0]}"
  local DIR=""
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  echo "$DIR"
}

function savePathes () {
  if [ ! -f "$stateFile" ]; # state file is declared in heureka bash main file
  then
    touch "$stateFile"
  fi

  local line_base="path_base=${gitPathes[base]}"
  local line_drops="path_drops=${gitPathes[drops]}"
  local line_arise="path_arise=${gitPathes[arise]}"
  local line_widget_user="path_widget_user=${gitPathes[widgetUser]}"
  local line_oauth_module="path_oauth_module=${gitPathes[oauthModule]}"
  echo "$line_base" >> "$stateFile"
  echo "$line_drops" >> "$stateFile"
  echo "$line_arise" >> "$stateFile"
  echo "$line_widget_user" >> "$stateFile"
  echo "$line_oauth_module" >> "$stateFile"
}

function readPathes () {
  if [ -f "$stateFile" ] # state file is declared in heureka bash main file
  then
    source "$stateFile"
    gitPathes[base]=$path_base
    gitPathes[drops]=$path_drops
    gitPathes[arise]=$path_arise
    gitPathes[widgetUser]=$path_widget_user
    gitPathes[oauthModule]=$path_oauth_module
  fi
}
