#!/bin/bash

source "git-setup.cfg"

source "commands/git-clone-rm"
source "commands/docker"

function init () {
  printf "Welcome to HEUREKA!\nSetup a development environment to implement the microservice DROPS."
  createGITPathes
  printf "\n"

  for (( ; ; ))
  do
    read -p "heureka> " cmd
    case "$cmd" in
	"git")
	  gitClone
	  ;;
	"rm")
	  gitRemove
	  ;;
	"docker up")
	  dockerRun
	  ;;
	"docker rm")
	  dockerRm
	  ;;
	"exit") exit 1
	  ;;
	# Todo: catch arrow up and down
    esac
  done
}

init

# TODO: start docker; start local develop systems
