version: "3.9"  # optional since v1.27.0
services:
  arise:
    image: soteto/arise:${ARISE_TAG}
    #build: ./repos/arise
    container_name: arise
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: ${ARISE_IP}
  
  drops:
    image: soteto/drops:${DROPS_TAG}
    container_name: drops
    restart: unless-stopped
#    links:
#      - nats
#      - drops-database
    volumes:
      - ./.docker-conf/mode_prod/drops/application.conf:/opt/docker/conf/application.conf
    networks:
      pool-network:
        ipv4_address: ${DROPS_IP}

  drops-database:
    image: "mariadb:${DROPS_DB_TAG}"
    container_name: drops-database
    restart: unless-stopped
    volumes:
      - ./.docker-volumes/mode_prod/drops-database/:/var/lib/mysql/
    # Required for access from local running drops
    #    ports:
    #      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DROPS_DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DROPS_DB_NAME}"
      MYSQL_USER: "${DROPS_DB_USER}"
      MYSQL_PASSWORD: "${DROPS_DB_PASS}"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      pool-network:
        ipv4_address: ${DROPS_DB_IP}

  #############
  # Dispenser #
  #############

  dispenser:
    volumes:
      - ./.docker-conf/mode_prod/dispenser/application.conf:/opt/docker/conf/application.conf
      - ./.docker-conf/mode_prod/navigation/:/opt/docker/conf/navigation/jsons/

  dispenser-database:
    volumes: 
       - ./.docker-volumes/mode_prod/dispenser-database/:/data/db/

  ################
  # Architecture #
  ###############

  nginx-pool:
    volumes:
      - ./.docker-conf/mode_prod/nginx/:/etc/nginx/conf.d/
