#!/bin/bash
set -e

# $1 is the current mode ("prod", "dev", "infra")
function prodDropsAdmin () {
  case $1 in
    "prod") source "$WORKDIR/.docker-conf/mode_prod/.env";;
    "infra") source "$WORKDIR/.docker-conf/mode_infra/.env";;
    *) source "$WORKDIR/microservices/ms-$1/.docker-conf/.env";;
  esac
  read -p "Please enter the email of the user that becomes an admin: " email
  local update="UPDATE User SET roles='supporter,admin' WHERE id=(SELECT user_id FROM Profile WHERE email='$email');"
  sudo docker exec -it drops-database mysql -u "$DROPS_DB_USER" -p"$DROPS_DB_PASS" "$DROPS_DB_NAME" -e "$update"
}
