#!/bin/bash
set -e

export WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

function ariseUp () {
  # TODO
  echo "Not implemented yet!"
}

function ariseDown () {
  # TODO
  echo "Not implemented yet!"
}

function ariseMan () {
  printf "Starting the ARISE frontend service should be done manually by the user to have full control. Open a new terminal window and change to '${gitPathes[base]}${gitPathes[arise]}'. Run the command 'npm run serve' and ARISE should start.\n"
}
