#!/bin/bash
set -e

export WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

source "$WORKDIR/.docker-conf/docker-compose/.env.dev.drops"

function dropsUp () {
  # TODO
  # cd "${gitPathes[base]}${gitPathes[drops]}"
  # sbt clean
  # sbt compile
  # sbt run &
  # cd "$WORKDIR"
  echo "Not implemented yet!"
}

function dropsDown () {
  # TODO
  echo "Not implemented yet!"
}

function dropsMan () {
  printf "Starting the DROPS backend service should be done manually by the user to have full control. Open a new terminal window and change to '${gitPathes[base]}${gitPathes[drops]}'. Run the command 'sbt run' and DROPS should start.\n\n"
  printf "Next step: Make a request to DROPS at the started port (e.g. 'localhost:9000/drops/') to initiate the database creation. This requires some time. Therefore, calling the nginx proxy will lead to a timeout HTTP error. DROPS itself is configured to wait 30 seconds.\n\n"
  printf "Afterwards, you should also start ARISE, create a user and run 'drops admin' to grant admin rights to the newly created user.\n"
}

function dropsAdmin () {
  read -p "Please enter the email of the user that becomes an admin: " email
  local update="UPDATE User SET roles='supporter,admin' WHERE id=(SELECT user_id FROM Profile WHERE email='$email');"
  sudo docker exec -it drops-database mysql -u "$DROPS_DB_USER" -p "$DROPS_DB_NAME" -e "$update"
}
