#!/bin/bash
set -e

confFile=".heureka.conf"

typeset -A config # init array

config=( # set default values in config array
  [env]="Not selected"
  [running_environment]="-"
  [running]="no"
)

readHeurekaConf() {
  while IFS= read -r line
  do
    if echo $line | grep -F = &>/dev/null
    then
        varname=$(echo "$line" | cut -d '=' -f 1)
        config[$varname]=$(echo "$line" | cut -d '=' -f 2-)
    fi
  done <"$confFile"
}

# $1 = the configuration parameter that has to be changed
# $2 = the new value for the configuration parameter
writeConfig() {
  target="$1"
  value="$2"
  sed -i "s/\($target *= *\).*/\1$value/" $confFile
}

# $1 = the configuration parameter that has to be changed
# $2 = the new value for the configuration parameter
setConfig() {
  writeConfig "$1" "$2"
  if [[ $1 = "running" && $2 = "yes" ]]; then
    writeConfig "running_environment" "${config[env]}"
  fi
  if [[ $1 = "running" && $2 = "no" ]]; then
    writeConfig "running_environment" "-"
  fi
  readHeurekaConf
}

# Set selected environment to "Not supported", if nothing is running.
setEnvToIdle() {
  # if nothing is running
  #if [[ ${config[running]} = "no" ]]; then
    # set environment to "Not selected"
    newEnv="Not selected"
    setConfig "env" "$newEnv"
  #fi
}

getEnv() {
  local selected="${config[env]}"
  if [[ $selected = "Not selected" && ${config[running_environment]} != "-" ]]; then
    selected="${config[running_environment]}"
  fi
  echo "$selected"
}

# Returns a string extending the prompt with context information
# $1 = Highlight color code
# $2 = Second color code
# $3 = Alert color code
# $3 = Default color code
getPromptExt() {
    local cleanEnv="${config[env]// /${1}-${2}}"
    local cleanRunningEnv="${config[running_environment]// /${1}-${2}}"
    local promptExt="${4}"
    if [[ ${config[env]} != "Not selected" ]]; then
      promptExt=$(echo -e "${4} in ${2}${cleanEnv}${4}")
    fi
    case "${config[running]}" in
      "yes")
        echo -e "$promptExt while ${2}${cleanRunningEnv}${4} is ${3}UP${4}"
	;;
      "stopped")
        echo -e "$promptExt while ${2}${cleanRunningEnv}${4} is ${2}STOPPED${4}"
	;;
      "no")
        echo -e "$promptExt"
	;;
    esac
}

# $1 = Highlight color code
# $2 = Second color code
# $3 = Default color code
printCurrentConf() {
  echo -e "
${1}Environment:${3} ${2}${config[env]}${3}
${1}Running:${3} ${2}${config[running]}${3} in ${2}${config[running_environment]}${3}"
}
