#!/bin/bash
set -e

export WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

function clone() {
  #echo "git clone --branch $3 $2 $1"
  if [[ -d "$1" && "$(ls -A $1)" ]]; then
    printf "Directory $1 is not empty.\n"
  else
    git clone --branch $3 $2 $1
  fi
}

function gitClone () {
  case "$1" in
    "drops")
      gitCloneDrops
      # Always required to have a running local documentation
      gitCloneDocu
    ;;
    "infra")
      gitCloneInfra
      # Always required to have a running local documentation
      gitCloneDocu
    ;;
  esac
}

function gitCloneDrops () {
  clone $(expandPath "${drops[path]}") "${drops[url]}" "${drops[branch]}"
  clone $(expandPath "${arise[path]}") "${arise[url]}" "${arise[branch]}"
  clone $(expandPath "${widgetUser[path]}") "${widgetUser[url]}" "${widgetUser[branch]}"
  clone $(expandPath "${oauthModule[path]}") "${oauthModule[url]}" "${oauthModule[branch]}"
}

function gitCloneInfra () {
  clone $(expandPath "${grav_dockerfile[path]}") "${grav_dockerfile[url]}" "${grav_dockerfile[branch]}"
  clone $(expandPath "${dispenser[path]}") "${dispenser[url]}" "${dispenser[branch]}"
  clone $(expandPath "${dispenser_navigation_widget[path]}") "${dispenser_navigation_widget[url]}" "${dispenser_navigation_widget[branch]}"
  clone $(expandPath "${navigationWidget[path]}") "${navigationWidget[url]}" "${navigationWidget[branch]}"
  clone $(expandPath "${vcaWidgetBase[path]}") "${vcaWidgetBase[url]}" "${vcaWidgetBase[branch]}"
  clone $(expandPath "${heurekaWidgetNavigation[path]}") "${heurekaWidgetNavigation[url]}" "${heurekaWidgetNavigation[branch]}"
}

function gitCloneDocu () {
  clone $(expandPath "${docu[path]}") "${docu[url]}" "${docu[branch]}"
}

function gitRemove () {
  case "$1" in
    "drops") gitRemoveDrops;;
    "infra") gitRemoveInfra;;
    "docu") gitRemoveDocu;;
  esac
}

function gitRemoveDocu () {
  rm -rf $(expandPath "${docu[path]}")
}

function gitRemoveInfra () {
grav-dockerfile
  rm -rf $(expandPath "${grav_dockerfile[path]}")
  rm -rf $(expandPath "${dispenser[path]}")
  rm -rf $(expandPath "${dispenser_navigation_widget[path]}")
  rm -rf $(expandPath "${navigationWidget[path]}")
  rm -rf $(expandPath "${vcaWidgetBase[path]}")
  rm -rf $(expandPath "${heurekaWidgetNavigation[path]}")
}

function gitRemoveDrops () {
  rm -rf $(expandPath "${drops[path]}")
  rm -rf $(expandPath "${arise[path]}")
  rm -rf $(expandPath "${widgetUser[path]}")
  rm -rf $(expandPath "${oauthModule[path]}")

  # Todo: Remove all empty directories of the base path.
}
