#!/bin/bash
set -e

export WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

source "$WORKDIR/git-setup.cfg"

declare -A gitPathes
declare -A gitURLs
declare -A gitBranch

gitURLs[drops]=$drops_url
gitURLs[arise]=$arise_url
gitURLs[widgetUser]=$widget_user_url
gitURLs[oauthModule]=$oauth_module_url

gitBranch[drops]=$drops_branch
gitBranch[arise]=$arise_branch
gitBranch[widgetUser]=$widget_user_branch
gitBranch[oauthModule]=$oauth_module_branch

function readPathes () {
  if [ -f "$stateFile" ] # state file is declared in heureka bash main file
  then
    source "$stateFile"
    gitPathes[base]=$path_base
    gitPathes[drops]=$path_drops
    gitPathes[arise]=$path_arise
    gitPathes[widgetUser]=$path_widget_user
    gitPathes[oauthModule]=$path_oauth_module
  fi
}

function clone() {
  git clone --branch $3 $2 "${gitPathes[base]}$1"
}

function gitClone () {
  readPathes
  mkdir -p "${gitPathes[base]}"

  clone "${gitPathes[drops]}" "${gitURLs[drops]}" "${gitBranch[drops]}"
  clone "${gitPathes[arise]}" "${gitURLs[arise]}" "${gitBranch[arise]}"
  clone "${gitPathes[widgetUser]}" "${gitURLs[widgetUser]}" "${gitBranch[widgetUser]}"
  clone "${gitPathes[oauthModule]}" "${gitURLs[oauthModule]}" "${gitBranch[oauthModule]}"

}

function gitRemove () {
  readPathes
  rm -rf "${gitPathes[base]}${gitPathes[drops]}"
  rm -rf "${gitPathes[base]}${gitPathes[arise]}"
  rm -rf "${gitPathes[base]}${gitPathes[widgetUser]}"
  rm -rf "${gitPathes[base]}${gitPathes[oauthModule]}"

  # Todo: Remove all empty directories of the base path.
}
