#!/bin/bash
set -e

export WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

source "$WORKDIR/git-setup.cfg"

declare -A gitPathes

function getBase () {
  local separated=""
  local base=""
  read -p "Do you want to enter one common base path for all repositories? [Y,n] " separated
  case "$separated" in
	Yes|yes|Y|y|"")
	    local DIR="$(getDir)"
	    DIR=${DIR%/*} # see https://tldp.org/LDP/LG/issue18/bash.html
	    read -p "Enter the base path [$DIR]: " -e base
	    if [[ $base == "" || -z $base ]]; then
		base=$DIR
	    fi
	    ;;
	No|no|N|n) base=""
	    ;;
	*) echo "Please answer 'Yes' or 'No'."
           exit 1
            ;;
  esac
  echo "$base"
}

function getRepoPath () {
  local path
  read -p "Enter a $3path for the repository of the $2 system $1 [$1]: " -e path
  case "$path" in
        $1|"") path="$1"
            ;;
  esac
  echo "$path"
}

function createGITPathes () {
  printf "Several GIT repositories have to be cloned.\nThus, you can define a base path for all the repositories or you can enter a path for each repository.\n\n"
  local basePath="$(getBase)"
  local sub="sub"
  if [[ -z $basePath ]]; then
    sub=""
  fi
  if [[ $basePath != *"/" && -n $basePath ]]; then
    basePath="$basePath/"
  fi
  gitPathes[base]=$basePath
  printf "\n"
  gitPathes[drops]="$(getRepoPath $drops_name backend $sub)"
  gitPathes[arise]="$(getRepoPath $arise_name frontend $sub)"
  gitPathes[widgetUser]="$(getRepoPath $widget_user_name widget $sub)"
  gitPathes[oauthModule]="$(getRepoPath $oauth_module_name module $sub)"
}

function savePathes () {
  if [ ! -f "$stateFile" ]; # state file is declared in heureka bash main file
  then
    touch "$stateFile"
  fi

  local line_base="path_base=${gitPathes[base]}"
  local line_drops="path_drops=${gitPathes[drops]}"
  local line_arise="path_arise=${gitPathes[arise]}"
  local line_widget_user="path_widget_user=${gitPathes[widgetUser]}"
  local line_oauth_module="path_oauth_module=${gitPathes[oauthModule]}"
  echo "$line_base" >> "$stateFile"
  echo "$line_drops" >> "$stateFile"
  echo "$line_arise" >> "$stateFile"
  echo "$line_widget_user" >> "$stateFile"
  echo "$line_oauth_module" >> "$stateFile"
}

function readPathes () {
  if [ -f "$stateFile" ] # state file is declared in heureka bash main file
  then
    source "$stateFile"
    gitPathes[base]=$path_base
    gitPathes[drops]=$path_drops
    gitPathes[arise]=$path_arise
    gitPathes[widgetUser]=$path_widget_user
    gitPathes[oauthModule]=$path_oauth_module
  fi
}

function initPathes () {
  readPathes
  if [ -z "${gitPathes[drops]}" ] && [ -z "${gitPathes[arise]}" ] && [ -z "${gitPathes[widgetUser]}" ] && [ -z "${gitPathes[oauthModule]}" ]; then
    createGITPathes
    savePathes
  else
    printf "\nAll pathes were read from '.state' file. You have entered the pathes before."
  fi
}
