#!/bin/bash
set -e

##############
# DEPRICATED #
##############

export WORKDIR=$(cd $(dirname $0) && pwd)
. "$WORKDIR/common"

function getBase () {
  local separated=""
  local base=""
  read -p "Do you want to enter one common base path for all repositories? [Y,n] " separated
  case "$separated" in
	Yes|yes|Y|y|"")
	    local DIR="$(getDir)"
	    DIR=${DIR%/*} # see https://tldp.org/LDP/LG/issue18/bash.html
	    read -p "Enter the base path [$DIR]: " -e base
	    if [[ $base == "" || -z $base ]]; then
		base=$DIR
	    fi
	    ;;
	No|no|N|n) base=""
	    ;;
	*) echo "Please answer 'Yes' or 'No'."
           exit 1
            ;;
  esac
  echo "$base"
}

function getRepoPath () {
  local path
  read -p "Enter a $3path for the repository of the $2 system $1 [$1]: " -e path
  case "$path" in
        $1|"") path="$1"
            ;;
  esac
  echo "$path"
}

function createGITPathes () {
  printf "Several GIT repositories have to be cloned.\nThus, you can define a base path for all the repositories or you can enter a path for each repository.\n\n"
  local basePath="$(getBase)"
  local sub="sub"
  if [[ -z $basePath ]]; then
    sub=""
  fi
  if [[ $basePath != *"/" && -n $basePath ]]; then
    basePath="$basePath/"
  fi
  gitPathes[base]=$basePath
  printf "\n"
  gitPathes[drops]="$(getRepoPath ${drops[name]} backend $sub)"
  gitPathes[arise]="$(getRepoPath ${arise[name]} frontend $sub)"
  gitPathes[widgetUser]="$(getRepoPath ${widgetUser[name]} widget $sub)"
  gitPathes[oauthModule]="$(getRepoPath ${oauthModule[name]} module $sub)"
}

function initPathes () {
#  readPathes - removed
  if [ -z "${gitPathes[drops]}" ] && [ -z "${gitPathes[arise]}" ] && [ -z "${gitPathes[widgetUser]}" ] && [ -z "${gitPathes[oauthModule]}" ]; then
    createGITPathes
#    savePathes - removed
  else
    printf "\nAll pathes were read from '.state' file. You have entered the pathes before."
  fi
}
