#!/bin/bash
set -e

function manHeader () {
  local environment=""
  if [ -n "$1" ]; then
    environment=$1"-"
  fi

  local header=""
  if [ -n "$2" ]; then
    header="\n"$2
  fi
  echo -e "
${YELLOW}HEUREKA ${environment}CLI${NC}${header}
Version: $(cat $MAINWORKDIR/VERSION)
Usage: [command]
Commands:"
}

function generalMan () {
  local ms_descs=""
  for ms in "${MICROSERVICES[@]}"; do
    local cmd_ms=$ms"_command"
    local cmd_desc=$ms"_description"
    ms_descs=$ms_descs"  "$(eval $cmd_ms)"                     ${RED}Microservice:${NC} "$(eval $cmd_desc)"\n"
  done
  manHeader "" "Setup a development environment to implement microservices for the HEUREKA platform.\n$(printCurrentConf $YELLOW $LIGHTBLUE $NC)\n"
  echo -e "
  ${YELLOW}prod${NC}                      Start production environment
  ${YELLOW}new${NC}                       Starts a wizard to initiate a development environment for a new microservice
$ms_descs
  infra                     ${RED}Additional:${NC} Initiate a development environment for infrastructure services
  ${YELLOW}exit${NC}                      Close console
  ${YELLOW}*${NC}                         Help
"
}

function msMan () {
  manHeader "DEVELOPMENT" "MICROSERVICE: $1"
}

function prodMan () {
  manHeader "PRODUCTION"
  echo -e "
  up                            Start the `docker-compose up` considering the `.docker-conf/mode_prod/.env` file
  stop                          Stop all created containers.
  rm                            Stop and remove all docker containers described in the docker-compose files
  rm drops volumes              Remove the drops volumes. That means the database contents.
  rm dispenser volumes          Remove the dispenser volumes. That means the database contents.
  admin                         Sets admin access rights in DROPS for a specific user identified by its email address
  leave                         Leave PROD environment
  exit                          Close console
  *                             Help
"
}

function infraMan () {
  manHeader "DEVELOPMENT" "INFRASTRUCTURE REQUIRED TO RUN MICROSERVICES"
  echo -e "
  clone                         Clone the required git repositories
  rm                            Remove the git repositories excluding the documentatuin contents
  rm docu                       Remove the git repositories including the documentation contents
  docker up                     Start the `docker-compose up` considering the `.docker-conf/mode_infra/.env` file (starts the dispenser database on `localhost:27017`)
  docker rm                     Stop and remove all docker containers described in the docker-compose file
  docker rm dispenser volumes   Remove the dispenser volumes. That means the database contents.
  leave                         Leave INFRA environment
  exit                          Close console
  *                             Help
"
}

function man () {
  case "$1" in
     "MAIN") generalMan;;
     "PROD") prodMan $1;;
     "INFRA") infraMan;;
     "MS") msMan $2;;
  esac
}

