version: "3.9"  # optional since v1.27.0
services:
  drops-database:
    image: "mariadb:${DROPS_DB_TAG}"
    container_name: drops-database
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes: 
       - ./.docker-volumes/mode_ms_drops/drops-database/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "${DROPS_DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DROPS_DB_NAME}"
      MYSQL_USER: "${DROPS_DB_USER}"
      MYSQL_PASSWORD: "${DROPS_DB_PASS}"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      pool-network:
        ipv4_address: ${DROPS_DB_IP}

  #############
  # Dispenser #
  #############

  dispenser:
    volumes:
      - ./microservices/ms-drops/.docker-conf/dispenser/application.conf:/opt/docker/conf/application.conf
      - ./microservices/ms-drops/.docker-conf/navigation/:/opt/docker/conf/navigation/jsons/
    ports:
      - 7000:9000

  dispenser-database:
    volumes: 
       - ./.docker-volumes/mode_ms_drops/dispenser-database/:/data/db/
    # Required for access from local running dispenser
    ports:
       - 27017:27017

  ################
  # Architecture #
  ###############

  nginx-pool:
    volumes:
      - ./microservices/ms-drops/.docker-conf/nginx/:/etc/nginx/conf.d/
    extra_hosts:
      # make 'localhost' ports available in nginx container by using 'host.docker.internal'
      - "host.docker.internal:host-gateway"

  nats:
    ports:
      - 4222:4222
